### PR TITLE
fixing call to missing field in whitelist table

### PR DESCRIPTION
**Pull request by zomGreg**
Fixes https://github.com/emxsys/callattendant/issues/16

### CODE REVIEW

**Comment by emxsys** [comment]
Greg, 
Thanks for the pull request! Especially the installation section.
I think the fix is to actually add the REASON field to the whitelist table.  The UI code references in it several places.  
I probably manually added the REASON field to my whitelist and forgot to change whitelist.py.  My fault. Sorry.
The WHITELIST.REASON field provides a mechanism to display why number is whitelisted, i.e., wife, son, friend, etc.

**Comment by zomGreg** [comment]
Ah, you're right. Shortsighted of me. Thanks for pointing that out.

**Comment by emxsys** [comment]
To keep things easy, how about I approve and merge the PR, and then we can reverse the change to webapp.py and fix the create whitelist table code. What do you think?


Bruce Schubert
KM6ZJK
Ventura CA
m: +1.805.207.1080
bruce@emxsys.com<mailto:bruce@emxsys.com>


________________________________

**Comment by zomGreg** [comment]
Nah, punt it back to me and I'll resubmit. The PR is a step backward. Plus,
this will give me a chance to practice. I do think there is a way to cherry
pick the commits so you'd only merge the changes to README and
requirements.txt. But if you don't want to mess with that (I don't remember
how to do that, like I said: rusty) just reject the whole thing.

**Comment by emxsys** [comment]
Closing this PR (vs merging) so the proper fix can be made to the CREATE TABLE sql in whitelist.py.

**Pull request closed without merging**
